### ISSUE TITLE
Regex taking too much time for long urls.

### ISSUE THREAD

**Issue by SrikanthYashaswi** [my-old-projects/ts-url-shortener#2]
https://github.com/aligoren/ts-url-shortener/blob/eee85262a85994c9888fec365921bee56b6f88b8/public/js/app.js#L6-L16

url with length > 35 hangs browser.

**Comment by aligoren** [comment]
Hmm. This was a simple URL validation snippet for years. I think this needs rewrite. What do you think?

**Comment by SrikanthYashaswi** [comment]
after u mentioned, i tested it independently. there is no problem there.
The problem is not here....

please check if its reproduced at ur side.

**Comment by aligoren** [comment]
Okay actually, this repository also needs tests? I think. What do  you think?

**Comment by SrikanthYashaswi** [comment]
Yup test would always be useful. but only for production deployments. But isn't it more for  educational purpose ?

**Comment by aligoren** [comment]
Yes, only educational. I couldn't test it yet. Most probably, I'll test it tomorrow.

**Comment by SrikanthYashaswi** [comment]
But I don't know if writing tests will be worth it.
